### PR TITLE
use our nexus apt repo

### PR DESCRIPTION
**Pull request by ken-adey**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. Ex: unit tests, manual tests)
(If this patch involves UI changes, please attach a screen-shot; otherwise, remove this)

Please review [Ambari Contributing Guide](https://cwiki.apache.org/confluence/display/AMBARI/How+to+Contribute) before opening a pull request.

### CODE REVIEW

**Review by jayhoughton — APPROVED** [review]
Can't see all the changes, i think my monitor is too small. But so far looks good.

**Review by sdrona — APPROVED** [review]
ok

**Review by sdrona — APPROVED** [review]
ok

**Review by jayhoughton — APPROVED** [review]
Yes

**Pull request merged**
